### ISSUE TITLE
Unable to call or receive calls on `omni-14-202404091525-zenfone9-GAPPS`

### ISSUE THREAD

**Issue by brian6932** [omnirom/android_device_asus_zenfone9#5]
Worked fine previously, calling results in an immediate disconnect. Receiving calls goes directly to voicemail. Reinstalling SIM doesn't help. Occurs on both stock build.prop and boot.img.

Still occurs on `14-202404301527-zenfone9-GAPPS`.

I see the following exceptions in logcat
```
04-30 14:21:55.210  2688  2688 E Telecom : InCallController: Package Manager could not find ComponentName: ComponentInfo{com.android.dialer/com.android.incallui.InCallServiceImpl}. Trying to bind anyway.: TSI.pC->CM.fOCP->CM.sOCPA->CM.dSMCP->CM.dSPA->CM.pASP(cgad)@EMY
04-30 14:21:55.210  2688  2688 E Telecom : java.lang.Exception
04-30 14:21:55.210  2688  2688 E Telecom :      at com.android.server.telecom.InCallController.getInCallServiceComponent(InCallController.java:2080)
04-30 14:21:55.210  2688  2688 E Telecom :      at com.android.server.telecom.InCallController.bindToServices(InCallController.java:1920)
04-30 14:21:55.210  2688  2688 E Telecom :      at com.android.server.telecom.InCallController.onCallAdded(InCallController.java:1353)
04-30 14:21:55.210  2688  2688 E Telecom :      at com.android.server.telecom.CallsManager.addCall(CallsManager.java:4383)
04-30 14:21:55.210  2688  2688 E Telecom :      at com.android.server.telecom.CallsManager.lambda$startOutgoingCall$11(CallsManager.java:2268)
04-30 14:21:55.210  2688  2688 E Telecom :      at com.android.server.telecom.CallsManager.$r8$lambda$ReExtwr9Kd8fbi7sMbxjjmf3yEI(CallsManager.java:0)
04-30 14:21:55.210  2688  2688 E Telecom :      at com.android.server.telecom.CallsManager$$ExternalSyntheticLambda13.apply(R8$$SyntheticClass:0)
04-30 14:21:55.210  2688  2688 E Telecom :      at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1126)
04-30 14:21:55.210  2688  2688 E Telecom :      at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:458)
04-30 14:21:55.210  2688  2688 E Telecom :      at com.android.server.telecom.LoggedHandlerExecutor$1.loggedRun(LoggedHandlerExecutor.java:41)
04-30 14:21:55.210  2688  2688 E Telecom :      at android.telecom.Logging.Runnable$1.run(Runnable.java:37)
04-30 14:21:55.210  2688  2688 E Telecom :      at android.os.Handler.handleCallback(Handler.java:959)
04-30 14:21:55.210  2688  2688 E Telecom :      at android.os.Handler.dispatchMessage(Handler.java:100)
04-30 14:21:55.210  2688  2688 E Telecom :      at android.os.Looper.loopOnce(Looper.java:232)
04-30 14:21:55.210  2688  2688 E Telecom :      at android.os.Looper.loop(Looper.java:317)
04-30 14:21:55.210  2688  2688 E Telecom :      at com.android.server.SystemServer.run(SystemServer.java:1002)
04-30 14:21:55.210  2688  2688 E Telecom :      at com.android.server.SystemServer.main(SystemServer.java:686)
04-30 14:21:55.210  2688  2688 E Telecom :      at java.lang.reflect.Method.invoke(Native Method)
04-30 14:21:55.210  2688  2688 E Telecom :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
04-30 14:21:55.210  2688  2688 E Telecom :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:856)

04-30 14:21:55.385 15291 15291 E AndroidRuntime: FATAL EXCEPTION: main
04-30 14:21:55.385 15291 15291 E AndroidRuntime: Process: org.codeaurora.ims, PID: 15291
04-30 14:21:55.385 15291 15291 E AndroidRuntime: java.lang.NoSuchMethodError: No static method isVosSupported(ILandroid/content/Context;)Z in class Lorg/codeaurora/ims/utils/QtiImsExtUtils; or its super classes (declaration of 'org.codeaurora.ims.utils.QtiImsExtUtils' appears in /product/framework/ims-ext-common.jar)
04-30 14:21:55.385 15291 15291 E AndroidRuntime:        at org.codeaurora.ims.ImsCallSessionImpl.updateImsCallProfile(ImsCallSessionImpl.java:1931)
04-30 14:21:55.385 15291 15291 E AndroidRuntime:        at org.codeaurora.ims.ImsCallSessionImpl.updateCall(ImsCallSessionImpl.java:377)
04-30 14:21:55.385 15291 15291 E AndroidRuntime:        at org.codeaurora.ims.ImsServiceClassTracker.handleCalls(ImsServiceClassTracker.java:246)
04-30 14:21:55.385 15291 15291 E AndroidRuntime:        at org.codeaurora.ims.ImsServiceSub.handleCalls(ImsServiceSub.java:1343)
04-30 14:21:55.385 15291 15291 E AndroidRuntime:        at org.codeaurora.ims.ImsServiceSub.-$$Nest$mhandleCalls(Unknown Source:0)
04-30 14:21:55.385 15291 15291 E AndroidRuntime:        at org.codeaurora.ims.ImsServiceSub$ImsServiceSubHandler.handleMessage(ImsServiceSub.java:1580)
04-30 14:21:55.385 15291 15291 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
04-30 14:21:55.385 15291 15291 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:232)
04-30 14:21:55.385 15291 15291 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:317)
04-30 14:21:55.385 15291 15291 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8501)
04-30 14:21:55.385 15291 15291 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-30 14:21:55.385 15291 15291 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
04-30 14:21:55.385 15291 15291 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
04-30 14:21:55.385  3778  3778 I ImsExternalCallTracker: onPhoneStateChanged : hasActiveCalls = true
```

**Comment by micky387** [comment]
Hi. I will check.

**Comment by micky387** [comment]
Probably fixed.
Merged recent CLO changes and especially this 
https://github.com/omnirom/android_vendor_codeaurora_telephony/commit/455a16e750468918a512399dc1c33480861fb69c

**Comment by micky387** [comment]
So fixed with the new OTA @brian6932 ?

**Comment by brian6932** [comment]
Was there a new OTA released?
I'm on
```
❯ adb shell getprop ro.omni.version
14-202404301527-zenfone9-GAPPS
```
and it doesn't work. Oh MICROG, Idk if the things I use work with MICROG tbh.

**Comment by micky387** [comment]
> Was there a new OTA released? I'm on
> 
> ```
> ❯ adb shell getprop ro.omni.version
> 14-202404301527-zenfone9-GAPPS
> ```
> 
> and it doesn't work. Oh MICROG, Idk if the things I use work with MICROG tbh.

ah , yes. wait for GAPPS OTA. Jenkins in progress

**Comment by micky387** [comment]
So fixed ?

**Comment by brian6932** [comment]
Yes, just updated
